/* Generated by tools/gen_symbols.py from port/symbols.csv. Do not edit. */
#pragma once

/* ---- DGROUP globals (offsets for DSB/DSW/DSS/DSL) */
#define DS_herc_graphics                             0x0042  /* platform, u16 */
#define DS_timer_installed                           0x0044  /* platform, u16 */
#define DS_herc_mode                                 0x0046  /* platform, u16 */
#define DS_gfx_mode_set                              0x0048  /* platform, u16 */
#define DS_menu_lines                                0x0242  /* platform, u16[7] */
#define DS_ega_present                               0x0250  /* platform, u16 */
#define DS_ega_lowres_sw                             0x0252  /* platform, u16 */
#define DS_g_vga                                     0x0254  /* video, u16 */
#define DS_mouse_allowed                             0x0262  /* platform, u16 */
#define DS_no_ega_park                               0x0280  /* platform, u16 */
#define DS_game_end_flags                            0x0282  /* race, u16 */
#define DS_drive_dest                                0x0284  /* race, i16 */
#define DS_anim_mode                                 0x0286  /* sound, u16 */
#define DS_g_anim_yoff                               0x02D0  /* video, i16 */
#define DS_needle_colour                             0x02D2  /* race, i16 */
#define DS_pal_intro_tab                             0x02D4  /* video, u8[16] */
#define DS_g_saved_page_b                            0x02E6  /* video, far Desc* */
#define DS_g_saved_page_a                            0x02EA  /* video, far Desc* */
#define DS_wheel_knob_xy                             0x031E  /* race, u8[49][2] */
#define DS_wheel_idx_shown                           0x0350  /* race, i16 */
#define DS_shifter_tab                               0x036E  /* race, 10-byte[3] */
#define DS_g_scheme_ega                              0x03A0  /* video, u8[] */
#define DS_g_scheme_cga                              0x03F0  /* video, u8[] */
#define DS_pal_shadow                                0x0440  /* video, u8[17] */
#define DS_pal_shadow_6                              0x0446  /* garage, u8 */
#define DS_pal_black_tab                             0x0452  /* video, u8[16] */
#define DS_pal_alt_tab                               0x0462  /* video, u8[17] */
#define DS_gear_names                                0x0482  /* race, near*[7] */
#define DS_pal_fatal_tab                             0x04AC  /* video, u8[16] */
#define DS_tq_head                                   0x0566  /* platform, i16 */
#define DS_tq_tail                                   0x0568  /* platform, i16 */
#define DS_tq_free                                   0x056A  /* platform, i16 */
#define DS_tq_next_due                               0x056C  /* platform, u32 */
#define DS_tq_entries                                0x0572  /* platform, 5 x 18 bytes */
#define DS_wait_deadline                             0x05CC  /* platform, u32 */
#define DS_wait_any_key                              0x05D0  /* platform, u16 */
#define DS_wait_key                                  0x05D2  /* platform, u16 */
#define DS_msg_ticks                                 0x05DC  /* game_flow, i16 */
#define DS_click_returns                             0x05DE  /* platform, u16 */
#define DS_timer_on                                  0x05E0  /* platform, u16 */
#define DS_mouse_dx                                  0x05E2  /* platform, i16 */
#define DS_mouse_dy                                  0x05E4  /* platform, i16 */
#define DS_mouse_acc_x                               0x05E6  /* platform, i16 */
#define DS_mouse_acc_y                               0x05E8  /* platform, i16 */
#define DS_mouse_shift_x                             0x05EA  /* platform, u16 */
#define DS_mouse_shift_y                             0x05EC  /* platform, u16 */
#define DS_mouse_left                                0x05EE  /* platform, u16 */
#define DS_mouse_right                               0x05F0  /* platform, u16 */
#define DS_mouse_present                             0x05F2  /* platform, u8 */
#define DS_ticks                                     0x05F8  /* platform, u32 */
#define DS_game_clock                                0x05FC  /* race, u32 */
#define DS_bios_ticks                                0x0600  /* platform, u32 */
#define DS_rt_base                                   0x0604  /* game_flow, u32 */
#define DS_chain_count                               0x0608  /* platform, u8 */
#define DS_race_step_count                           0x0609  /* platform, u8 */
#define DS_demo_active                               0x0610  /* platform, u16 */
#define DS_auto_drive                                0x0612  /* platform, u16 */
#define DS_pal_protect_tab                           0x0692  /* video, u8[16] */
#define DS_pal_cycle                                 0x0698  /* platform, u8[3] */
#define DS_demo_quit_done                            0x06A4  /* platform, u16 */
#define DS_demo_fast                                 0x06A6  /* platform, u8 */
#define DS_demo_waiting                              0x06A7  /* game_flow, u8 */
#define DS_demo_cycle                                0x06A8  /* game_flow, i16 */
#define DS_demo_prev_screen                          0x06AA  /* game_flow, i16 */
#define DS_demo_06ac                                 0x06AC  /* game_flow, i16 */
#define DS_demo_cursor_x                             0x06AE  /* platform, i16 */
#define DS_demo_cursor_y                             0x06B0  /* platform, i16 */
#define DS_demo_script_pos                           0x06B2  /* game_flow, i16 */
#define DS_demo_script                               0x06B4  /* game_flow, i16[] */
#define DS_isr_cursor_busy                           0x06E0  /* platform, u8 */
#define DS_vib_countdown                             0x06E2  /* sound, u16 */
#define DS_siren_count                               0x06E4  /* sound, u16 */
#define DS_limiter_count                             0x06E6  /* race, i16 */
#define DS_isr_race_busy                             0x06E8  /* platform, u8 */
#define DS_fire_prev                                 0x06E9  /* race, u8 */
#define DS_squeal_phase                              0x06EA  /* sound, u8 */
#define DS_g_slide_overlay                           0x0792  /* video, far Desc* */
#define DS_UI_TEXTS                                  0x239E  /* garage, char[200] */
#define DS_ad_buf                                    0x2990  /* garage, char[] */
#define DS_ask_buf                                   0x29F8  /* garage, char[] */
#define DS_garage_title                              0x29FF  /* garage, char[] */
#define DS_edit_name                                 0x2A2E  /* game_flow, char[16] */
#define DS_btn_change                                0x2A3E  /* garage, char[8] */
#define DS_lbl_squelch                               0x2BA9  /* sound, u16 */
#define DS_lbl_tunes                                 0x2BAB  /* sound, u16 */
#define DS_TEXTS                                     0x2C02  /* garage, char[1850] */
#define DS_joy_x                                     0x4718  /* platform, i16 */
#define DS_joy_y                                     0x471A  /* platform, i16 */
#define DS_joy_buttons                               0x471C  /* platform, u8 */
#define DS_joy_present                               0x471D  /* platform, u8 */
#define DS_joy_centre_x                              0x471E  /* platform, i16 */
#define DS_joy_centre_y                              0x4720  /* platform, i16 */
#define DS_joy_thr_x_lo                              0x4722  /* platform, i16 */
#define DS_joy_thr_x_hi                              0x4724  /* platform, i16 */
#define DS_joy_thr_y_lo                              0x4726  /* platform, i16 */
#define DS_joy_thr_y_hi                              0x4728  /* platform, i16 */
#define DS_cursor_x                                  0x472A  /* platform, i16 */
#define DS_cursor_y                                  0x472C  /* platform, i16 */
#define DS_kbd_dir_x                                 0x472E  /* platform, i8 */
#define DS_kbd_dir_y                                 0x472F  /* platform, i8 */
#define DS_kbd_last_dir                              0x4730  /* platform, i8[2] */
#define DS_click_held                                0x4732  /* platform, u8 */
#define DS_g_ptr_show                                0x4733  /* video, i8 */
#define DS_click_code                                0x4736  /* platform, u8 */
#define DS_click2_code                               0x4737  /* platform, u8 */
#define DS_click_x                                   0x4738  /* platform, i16 */
#define DS_click_y                                   0x473A  /* platform, i16 */
#define DS_click2_x                                  0x473C  /* platform, i16 */
#define DS_click2_y                                  0x473E  /* platform, i16 */
#define DS_kbd_dir_lock                              0x4740  /* platform, i16 */
#define DS_cursor_hot_x                              0x4742  /* platform, i16 */
#define DS_cursor_hot_y                              0x4744  /* platform, i16 */
#define DS_race_saved_cursor_x                       0x4746  /* race, i16 */
#define DS_race_saved_cursor_y                       0x4748  /* race, i16 */
#define DS_step_x                                    0x474C  /* platform, i16[3] indexed -1..1 */
#define DS_step_y                                    0x4752  /* platform, i16[3] indexed -1..1 */
#define DS_kbd_xlat                                  0x4766  /* platform, u8[57h] */
#define DS_demo_scancode                             0x47CC  /* game_flow, u8 */
#define DS_click_edge                                0x47CD  /* platform, u8 */
#define DS_sound_on                                  0x47CE  /* platform, u8 */
#define DS_speaker_on                                0x47CF  /* platform, u8 */
#define DS_key                                       0x47D0  /* platform, u8 */
#define DS_old_int9                                  0x47D4  /* platform, far ptr */
#define DS_joy_saved_sp                              0x47E8  /* platform, u16 */
#define DS_click_seen                                0x47EE  /* platform, u16 */
#define DS_PARTS                                     0x4806  /* garage, u8[44][8] */
#define DS_part_types                                0x4808  /* race, 8-byte[] */
#define DS_INIT_WEAR                                 0x4966  /* garage, i16[5] */
#define DS_races_total                               0x4970  /* race, i16 */
#define DS_drag_wins                                 0x4972  /* race, i16 */
#define DS_road_wins                                 0x4974  /* race, i16 */
#define DS_king_drag_won                             0x4976  /* race, i16 */
#define DS_MANIFOLD_FITS                             0x4978  /* garage, u8[3][5] */
#define DS_CARB_FITS                                 0x4988  /* garage, u8[5][3] */
#define DS_BAY_PICS                                  0x4998  /* garage, i16[5][5] */
#define DS_bay_block_pic                             0x49A2  /* garage, i16 */
#define DS_BOLT_PICS                                 0x49CA  /* garage, i16[4] */
#define DS_TRANS_PICS                                0x49D2  /* garage, i16[4] */
#define DS_list_items                                0x49E0  /* game_flow, i16[] */
#define DS_protect_table                             0x4B62  /* game_flow, u8[51*2] */
#define DS_pal_cycle_on                              0x4BC8  /* platform, u16 */
#define DS_hall_row_y                                0x4BCA  /* game_flow, i16[10] */
#define DS_msg_no_memory                             0x4BEE  /* platform, char[] */
#define DS_g_vram_pool_base                          0x4C14  /* video, far ptr */
#define DS_g_vram_pool_used                          0x4C18  /* video, u16[4] */
#define DS_big_pics                                  0x4C20  /* platform, u16[4] */
#define DS_resident_pics                             0x4C28  /* platform, u16[] */
#define DS_hot_data_name                             0x4EA2  /* platform, char * */
#define DS_hot_block_dst                             0x4EA4  /* platform, u16[13] */
#define DS_hot_block_size                            0x4EBE  /* platform, u16[13] */
#define DS_lib_handle                                0x4ED8  /* platform, u16[2] */
#define DS_lib_names                                 0x4EDC  /* platform, char *[4] */
#define DS_lib_msgs                                  0x4EE4  /* platform, char *[5] */
#define DS_decode_alloc                              0x4F0E  /* platform, u16 */
#define DS_hall_name                                 0x4F3A  /* platform, char[] */
#define DS_switch_old                                0x4F46  /* garage, CAR* */
#define DS_switch_new                                0x4F48  /* garage, CAR* */
#define DS_car_cache_valid                           0x4F4A  /* game_flow, i16 */
#define DS_game_pics_freed                           0x4F4C  /* game_flow, i16 */
#define DS_NEWS_PICS                                 0x4F4E  /* garage, i16[5] */
#define DS_headline                                  0x4F58  /* game_flow, i16 */
#define DS_headline_day                              0x4F5A  /* game_flow, i16 */
#define DS_slot_present                              0x4FC2  /* game_flow, u8[16] */
#define DS_slot_text                                 0x4FD4  /* game_flow, u16[15] */
#define DS_msg_need_name                             0x4FF2  /* game_flow, u16 */
#define DS_geek_index                                0x4FF4  /* game_flow, i16 */
#define DS_save_name_tmpl                            0x4FF6  /* game_flow, char[13] */
#define DS_TYRE_PICS                                 0x5030  /* garage, i16[3][4] */
#define DS_cal_x0                                    0x5048  /* game_flow, i16 */
#define DS_cal_y0                                    0x504A  /* game_flow, i16[4] */
#define DS_cal_row0                                  0x5052  /* game_flow, i16[4] */
#define DS_MONTH_NAME                                0x5082  /* garage, char*[4] */
#define DS_car_colour_pairs                          0x50C2  /* race, u8[][2] */
#define DS_manifold_carbs                            0x5126  /* race, i16[8] */
#define DS_BOLTS_PER_LAYER                           0x5130  /* garage, i16[5] */
#define DS_LAYER_CATEGORY                            0x513C  /* garage, i16[5] */
#define DS_BAY_LAYOUT                                0x5148  /* garage, i16[6][6] */
#define DS_BOLT_CTX                                  0x5184  /* garage, i16[] */
#define DS_bay_layout_cur                            0x518C  /* garage, i16[6] */
#define DS_BOLT_SIDE                                 0x5198  /* garage, i16[] */
#define DS_opp_pal_saved                             0x51AC  /* race, u8[2] */
#define DS_cruise_accel                              0x51D8  /* race, i16[6] */
#define DS_cruise_ratio                              0x51E2  /* race, i16[6] */
#define DS_skip_fx                                   0x51EC  /* race, i16 */
#define DS_last_pick                                 0x51F8  /* race, i16 */
#define DS_end_face0                                 0x526A  /* game_flow, u8[6] */
#define DS_end_faces                                 0x5270  /* game_flow, u8[19*6] */
#define DS_end_lips                                  0x52E2  /* game_flow, u8[9*6] */
#define DS_end_pics1                                 0x5318  /* game_flow, i16[] */
#define DS_end_pics2                                 0x5328  /* game_flow, i16[] */
#define DS_stats_done                                0x53E6  /* race, i16 */
#define DS_tire_slip_tab                             0x54B2  /* race, i16[3][5] */
#define DS_ai_steps_done                             0x54D0  /* race, i16 */
#define DS_ai_yield_toggle                           0x54D2  /* race, i16 */
#define DS_ai_in_curve                               0x54D6  /* race, i16 */
#define DS_ai_alongside_count                        0x54D8  /* race, i16 */
#define DS_ai_brake                                  0x54DA  /* race, i16 */
#define DS_gear_spread                               0x54DC  /* race, i16[4][5] */
#define DS_eng_torque                                0x5504  /* race, i16[3][5] */
#define DS_eng_bands                                 0x5522  /* race, i16[3][2] */
#define DS_intake_bonus                              0x552E  /* race, i16[3][5] */
#define DS_eng_bonus                                 0x554C  /* race, i16[3] */
#define DS_trans_bonus                               0x5552  /* race, i16[4] */
#define DS_eng_redline                               0x555A  /* race, i16[3] */
#define DS_trans_gears                               0x5560  /* race, i16[4] */
#define DS_tire_grip                                 0x5568  /* race, i16[3] */
#define DS_class_bonus                               0x556E  /* race, i16[] */
#define DS_kbd_remap_tables                          0x579F  /* platform, u16[42] */
#define DS_vib_wave                                  0x57F6  /* sound, s16[3][8] */
#define DS_vib_rec                                   0x5826  /* sound, struct[5] (10 bytes) */
#define DS_bg_loop_counts                            0x5858  /* sound, s16[19] */
#define DS_fx_loop_counts                            0x587E  /* sound, s16[2] */
#define DS_bg_vib_index                              0x5882  /* sound, u16[37] */
#define DS_fx_vib_index                              0x58CC  /* sound, u16[2] */
#define DS_music_enabled                             0x58D0  /* sound, u16 */
#define DS_music_cur                                 0x58D2  /* sound, u16 */
#define DS_music_mode                                0x58D4  /* sound, u16 */
#define DS_music_enabled_saved                       0x58D6  /* sound, s16 */
#define DS_music_muted                               0x58D8  /* sound, u16 */
#define DS_squeal_on                                 0x58DA  /* sound, u16 */
#define DS_siren_on                                  0x58DC  /* sound, u16 */
#define DS_pulse3_ptr                                0x58DE  /* sound, u16 */
#define DS_pulse3_delay                              0x58E0  /* sound, u16 */
#define DS_delay_scale                               0x58E2  /* sound, u16 */
#define DS_race_cga_dbl                              0x58E4  /* race, i16 */
#define DS_has_clock                                 0x58E6  /* race, u16 */
#define DS_wheel_pics                                0x58E8  /* race, i16[3] */
#define DS_race_run_passes                           0x58EE  /* race, i16 */
#define DS_anim_engine_snd                           0x5A0E  /* sound, u16 */
#define DS_saved_bios_mode                           0x5AEE  /* platform, u8 */
#define DS_saved_equip                               0x5AF0  /* platform, u8 */
#define DS_ega_mem                                   0x5AF1  /* platform, u8 */
#define DS_drv_table_cgaherc                         0x5B04  /* platform, far ptr[15] */
#define DS_g_vec_tandy                               0x5B8A  /* video, far ptr[15] */
#define DS_g_vec_ega                                 0x5BD0  /* video, far ptr[15] */
#define DS_g_blinds_rows                             0x5C0C  /* video, u16[5] */
#define DS_g_lmask                                   0x5C15  /* video, u8[9] */
#define DS_g_gc3                                     0x5C1E  /* video, u16 */
#define DS_hill_profile_22                           0x5C20  /* race, s16[22] */
#define DS_hill_profile_38                           0x5C4C  /* race, s16[38] */
#define DS_hill_profile_17                           0x5C98  /* race, s16[17] */
#define DS_course_len                                0x5CBA  /* race, s16 */
#define DS_course_layouts                            0x5CBC  /* race, s16[10][12] */
#define DS_page1_desc                                0x5DAC  /* race, Pic */
#define DS_page2_desc                                0x5DDC  /* race, Pic */
#define DS_course_layout                             0x5E0C  /* race, s16 */
#define DS_offroad                                   0x5E0E  /* race, u16 */
#define DS_nudge_right_latch                         0x5E10  /* race, u16 */
#define DS_nudge_left_latch                          0x5E12  /* race, u16 */
#define DS_car_class_pics                            0x5E14  /* race, s16[5][4] */
#define DS_back_page                                 0x5E3E  /* race, s16 */
#define DS_shown_page                                0x5E40  /* race, s16 */
#define DS_view_copy_rect                            0x5E42  /* race, Rect */
#define DS_g_span_xmin                               0x5E4E  /* video, i16 */
#define DS_g_span_ymin                               0x5E50  /* video, i16 */
#define DS_g_span_ymax                               0x5E52  /* video, i16 */
#define DS_g_span_xmax                               0x5E54  /* video, i16 */
#define DS_shrink_masks_rear                         0x5E56  /* race, u8[4] */
#define DS_shrink_masks_far                          0x5E5A  /* race, u8[4] */
#define DS_shrink_masks_front                        0x5E5E  /* race, u8[4] */
#define DS_loc_sign_sheet                            0x5E62  /* race, s16[4] */
#define DS_dash_width_front                          0x5E6A  /* race, s16[15] */
#define DS_dash_width_mirror                         0x5E84  /* race, s16[8] */
#define DS_sign_sizes                                0x5E9C  /* race, s16[7][3] */
#define DS_opp_substep_frac                          0x5EC6  /* race, s16 */
#define DS_shape_table                               0x6078  /* race, u16[20] */
#define DS_hydrant_shape                             0x607C  /* race, u16 */
#define DS_dot_shape                                 0x60A0  /* race, u16 */
#define DS_g_desc_seg                                0x68E2  /* video, u16 */
#define DS_g_font_seg2                               0x691A  /* video, u16 */
#define DS_picdir_seg                                0x691C  /* platform, u16 */
#define DS_g_font_seg                                0x6A2A  /* video, u16 */
#define DS_seg389b_centre                            0x6A2C  /* race, u16 */
#define DS_wheel_pic_ptrs                            0x6C28  /* race, far Desc*[3] */
#define DS_shifter_rec                               0x6C34  /* race, near* */
#define DS_shifter_pos                               0x6C36  /* race, i16 */
#define DS_cursor_drawn_x                            0x6C46  /* platform, i16 */
#define DS_cursor_drawn_y                            0x6C48  /* platform, i16 */
#define DS_cursor_moved                              0x6C4A  /* platform, u8 */
#define DS_screen_id                                 0x6C4C  /* platform, u16 */
#define DS_last_click_code                           0x6C4E  /* platform, u8 */
#define DS_demo_pick                                 0x6C50  /* game_flow, i16 */
#define DS_vib_amount                                0x6C52  /* sound, u16 */
#define DS_vib_last_div                              0x6C54  /* sound, u16 */
#define DS_hall_new_score                            0x6C5E  /* game_flow, i16 */
#define DS_dgroup_seg                                0x6C60  /* platform, u16 */
#define DS_rnd_s1                                    0x6C62  /* platform, i16 */
#define DS_rnd_s2                                    0x6C64  /* platform, i16 */
#define DS_rnd_s3                                    0x6C66  /* platform, i16 */
#define DS_cur_drive                                 0x6C68  /* platform, u16 */
#define DS_cur_lib_count                             0x6C6A  /* platform, u16 * */
#define DS_cur_lib_handle                            0x6C6C  /* platform, u16 * */
#define DS_cur_lib_name                              0x6C6E  /* platform, char * */
#define DS_other_lib_handle                          0x6C70  /* platform, u16 * */
#define DS_hot_data_path                             0x6C72  /* platform, char[] */
#define DS_cruise_gain                               0x6C82  /* race, i16 */
#define DS_waitress_state                            0x6C84  /* race, i16 */
#define DS_cand_count                                0x6C86  /* race, i16 */
#define DS_drink_ordered                             0x6C88  /* race, i16 */
#define DS_cand                                      0x6C8A  /* race, i16[] */
#define DS_track_end                                 0x6CAA  /* race, i16 */
#define DS_opp_vmax                                  0x6CAC  /* race, i16 */
#define DS_opp_slack                                 0x6CAE  /* race, i16 */
#define DS_opp_v80                                   0x6CB0  /* race, i16 */
#define DS_opp_v70                                   0x6CB2  /* race, i16 */
#define DS_opp_skill                                 0x6CB4  /* race, i16 */
#define DS_opp_lat_target                            0x6CB6  /* race, i16 */
#define DS_opp_band_tmp                              0x6CB8  /* race, u16 */
#define DS_opp_shift_rpm                             0x6CBA  /* race, i16 */
#define DS_arena                                     0x6CD0  /* platform, far ptr */
#define DS_build_yaw                                 0x6DFE  /* race, s16 */
#define DS_build_seg                                 0x6E00  /* race, s16 */
#define DS_build_yaw_step                            0x6E02  /* race, s16 */
#define DS_ground_top_y                              0x6E04  /* race, s16 */
#define DS_top_band_row                              0x6E06  /* race, s16 */
#define DS_row_ptr_xl                                0x6E08  /* race, u16 */
#define DS_left_ptr                                  0x6E20  /* race, far u16* */
#define DS_right_ptr                                 0x6E24  /* race, far u16* */
#define DS_dash_ptr                                  0x6E28  /* race, u16 */
#define DS_opp_sprite_prev2                          0x6E2A  /* race, s16 */
#define DS_pic_start_light                           0x6E60  /* race, Pic far* */
#define DS_g_slide_overlay_rect                      0x70AC  /* video, Rect */
#define DS_ai_edge_left                              0x70C0  /* race, s16 */
#define DS_mir_xol                                   0x70C2  /* race, s16[8] */
#define DS_mir_xor                                   0x70D2  /* race, s16[8] */
#define DS_libs_preloaded                            0x70E2  /* platform, u16 */
#define DS_MODEL_HOTSPOTS                            0x70E4  /* garage, u8[26][20] */
#define DS_vib_enabled                               0x72EC  /* sound, u16 */
#define DS_seg_left_ptr                              0x72EE  /* race, far u16* */
#define DS_opp_rear_end                              0x72F2  /* race, u16 */
#define DS_pic_pillar                                0x72F4  /* race, Pic far* */
#define DS_row_xl                                    0x72F8  /* race, s16[15] */
#define DS_g_page                                    0x7316  /* video, far Desc*[4] */
#define DS_police_sprites                            0x7526  /* race, Pic far*[13] */
#define DS_police_seg                                0x755A  /* race, i16 */
#define DS_seg_yaw_ptr                               0x7560  /* race, far s16* */
#define DS_pack_buf                                  0x7564  /* platform, far ptr */
#define DS_avg_speed                                 0x7644  /* race, i16 */
#define DS_hall_count                                0x7646  /* platform, u16 */
#define DS_opp_model                                 0x7648  /* race, i16 */
#define DS_pic_town_skyline                          0x764A  /* race, Pic far* */
#define DS_player_won                                0x7676  /* race, i16 */
#define DS_page0_ptr                                 0x7678  /* race, Pic far* */
#define DS_g_draw_off                                0x767C  /* video, u16 */
#define DS_pic_mountains                             0x767E  /* race, Pic far* */
#define DS_MODEL_LAYOUT                              0x7682  /* garage, u8[26][12] */
#define DS_STICKERS                                  0x7844  /* garage, i16[9][3] */
#define DS_g_draw_seg                                0x787A  /* video, u16 */
#define DS_tires_blown                               0x787C  /* race, u8 */
#define DS_g_scheme                                  0x787E  /* video, u8 * */
#define DS_seg_hgt_ptr                               0x7880  /* race, far s16* */
#define DS_row_y                                     0x7884  /* race, s16[15] */
#define DS_drv_vec                                   0x78A2  /* video, far ptr[15] */
#define DS_player_phys                               0x78E0  /* race, phys (0xC2 bytes) */
#define DS_player_steer_in                           0x78E2  /* race, i16 */
#define DS_player_wheel                              0x78E4  /* race, i16 */
#define DS_player_blowout_seg                        0x78EA  /* race, i16 */
#define DS_player_tire_slip                          0x78EC  /* race, i16 */
#define DS_player_rpm                                0x78EE  /* race, i16 */
#define DS_player_rpm_up                             0x78F4  /* race, i16 */
#define DS_player_rpm_down                           0x78F6  /* race, i16 */
#define DS_player_gear                               0x78F8  /* race, i16 */
#define DS_player_gear_dirty                         0x78FA  /* race, i16 */
#define DS_player_ngears                             0x78FC  /* race, i16 */
#define DS_player_redline                            0x78FE  /* race, i16 */
#define DS_player_automatic                          0x7900  /* race, i16 */
#define DS_player_auto_shift_rpm                     0x7902  /* race, i16 */
#define DS_player_auto_mode                          0x7904  /* race, i16 */
#define DS_player_ratio                              0x7914  /* race, i16[5] */
#define DS_player_grip                               0x791E  /* race, i16 */
#define DS_player_cur_ratio                          0x7920  /* race, i16 */
#define DS_player_band                               0x7922  /* race, i16 */
#define DS_player_curve                              0x7924  /* race, 8-byte[5][3] */
#define DS_player_result                             0x799C  /* race, u16 */
#define DS_player_steps_at_stop                      0x799E  /* race, i16 */
#define DS_player_steps                              0x79A0  /* race, i16 */
#define DS_bet_kind                                  0x79A2  /* race, i16 */
#define DS_bet_amount                                0x79A4  /* race, i16 */
#define DS_race_state                                0x79A6  /* race, i16 */
#define DS_bg_song                                   0x79AA  /* sound, SongState (28 bytes) */
#define DS_fx_song                                   0x79C6  /* sound, SongState (28 bytes) */
#define DS_opp_phys                                  0x79E2  /* race, phys (0xC2 bytes) */
#define DS_opp_rpm                                   0x79F0  /* race, i16 */
#define DS_opp_gear_no                               0x79FA  /* race, i16 */
#define DS_opp_result                                0x7A9E  /* race, u16 */
#define DS_old_int8                                  0x7AAA  /* platform, far ptr */
#define DS_start_light_h                             0x7AAE  /* race, s16 */
#define DS_row_yeye                                  0x7AB0  /* race, s16[15] */
#define DS_row_xr                                    0x7ACE  /* race, s16[15] */
#define DS_g_ptr_save                                0x7AEC  /* video, far Desc* */
#define DS_forsale_head                              0x7D16  /* garage, i16 */
#define DS_ai_edge_right                             0x7D2E  /* race, s16 */
#define DS_seg                                       0x7D30  /* race, s16 */
#define DS_substep                                   0x7D32  /* race, s16 */
#define DS_step_per_frame                            0x7D34  /* race, s16 */
#define DS_cam_x                                     0x7D36  /* race, s16 */
#define DS_cam_y                                     0x7D38  /* race, s16 */
#define DS_heading                                   0x7D3C  /* race, s16 */
#define DS_cur_height                                0x7D3E  /* race, s16 */
#define DS_vs_king                                   0x7D40  /* race, i16 */
#define DS_seg_centre_ptr                            0x7D62  /* race, far u16* */
#define DS_lights_green                              0x7D66  /* race, i16 */
#define DS_opp_model_ptr                             0x7D7A  /* race, near* */
#define DS_opp_sprite                                0x7D7C  /* race, s16 */
#define DS_edge_left                                 0x7D82  /* race, s16 */
#define DS_opp_rec                                   0x7D84  /* race, near* */
#define DS_car_models                                0x7D86  /* race, 10-byte[26] */
#define DS_opp_seg                                   0x7E8A  /* race, i16 */
#define DS_opp_seg_frac                              0x7E8C  /* race, i16 */
#define DS_opp_seg_step                              0x7E8E  /* race, i16 */
#define DS_opp_lat                                   0x7E90  /* race, i16 */
#define DS_player_name                               0x7E9A  /* game_flow, char[16] */
#define DS_money                                     0x7EAA  /* race, i32 */
#define DS_unk_7eae                                  0x7EAE  /* game_flow, u16 */
#define DS_car                                       0x7EB0  /* race, near* */
#define DS_car2                                      0x7EB2  /* race, near* */
#define DS_car_freelist                              0x7EB4  /* game_flow, u16 */
#define DS_car_count                                 0x7EB6  /* game_flow, i16 */
#define DS_spare_parts                               0x7EB8  /* game_flow, u16 */
#define DS_part_freelist                             0x7EBA  /* game_flow, u16 */
#define DS_part_count                                0x7EBC  /* game_flow, i16 */
#define DS_race_type                                 0x7EC0  /* race, i16 */
#define DS_mir_xl                                    0x7F22  /* race, s16[8] */
#define DS_opp_index                                 0x7F82  /* race, i16 */
#define DS_opp_present                               0x7F86  /* race, u16 */
#define DS_police_state                              0x7F88  /* race, u16 */
#define DS_row_xol                                   0x7F8A  /* race, s16[15] */
#define DS_row_xor                                   0x7FD8  /* race, s16[15] */
#define DS_opponents                                 0x7FF8  /* race, 0x12-byte[22] */
#define DS_king_ready                                0x817D  /* race, u8 */
#define DS_pic_mirror                                0x8184  /* race, Pic far* */
#define DS_page1_ptr                                 0x8188  /* race, Pic far* */
#define DS_MODEL_POINTS                              0x818C  /* garage, u8[26][6] */
#define DS_g_front                                   0x822A  /* video, far Desc* */
#define DS_g_back                                    0x822E  /* video, far Desc* */
#define DS_driver_id                                 0x8236  /* video, i16 */
#define DS_g_nplanes                                 0x8238  /* video, u16 */
#define DS_g_px_shift                                0x823A  /* video, u16 */
#define DS_g_px_factor                               0x823C  /* video, u16 */
#define DS_g_x_align                                 0x823E  /* video, i16 */
#define DS_g_mirror                                  0x8240  /* video, u16 */
#define DS_g_text_fg                                 0x8242  /* video, u8 */
#define DS_g_text_bg                                 0x8243  /* video, u8 */
#define DS_g_fill_col                                0x8244  /* video, u8 */
#define DS_g_line_col                                0x8245  /* video, u8 */
#define DS_g_frame_style                             0x8246  /* video, u8 */
#define DS_g_ui_level                                0x8247  /* video, u8 */
#define DS_g_overscan                                0x8248  /* video, u8 */
#define DS_g_pal_visible                             0x8249  /* video, u8 */
#define DS_g_text_end_x                              0x824C  /* video, i16 */
#define DS_g_text_y                                  0x824E  /* video, i16 */
#define DS_car_x                                     0x825E  /* garage, i16 */
#define DS_car_y                                     0x8260  /* garage, i16 */
#define DS_sticker_x                                 0x8272  /* garage, i16 */
#define DS_sticker_y                                 0x8274  /* garage, i16 */
#define DS_bet_button                                0x8278  /* race, i16 */
#define DS_trans_pic                                 0x8286  /* garage, i16 */
#define DS_bay_slot_pic                              0x8290  /* garage, i16[5] */
#define DS_bay_bolt_pic                              0x829A  /* garage, i16[9] */
#define DS_bay_connector_pic                         0x82AC  /* garage, i16 */
#define DS_bay_ctx                                   0x82AE  /* garage, i16 */
#define DS_page2_ptr                                 0x82B4  /* race, Pic far* */
#define DS_distance                                  0x82BC  /* race, i32 */
#define DS_wheel_shown                               0x82C2  /* race, i16 */
#define DS_vib_rec_ptr                               0x82C4  /* sound, u16 */
#define DS_slow_machine                              0x82C6  /* platform, u16 */
#define DS_pct_covered                               0x82C8  /* race, i16 */
#define DS_hall_records                              0x82CA  /* platform, u8[230] */
#define DS_car_pool                                  0x83B0  /* game_flow, u8[16*0x28] */
#define DS_gear_label_shown                          0x8630  /* race, i16 */
#define DS_player_ahead                              0x8632  /* race, u16 */
#define DS_seg_right_ptr                             0x8634  /* race, far u16* */
#define DS_mir_y                                     0x8638  /* race, s16[8] */
#define DS_mir_yeye                                  0x864A  /* race, s16[8] */
#define DS_mir_xr                                    0x865A  /* race, s16[8] */
#define DS_part_pool                                 0x866A  /* game_flow, u8[140*8] */
#define DS_racing                                    0x8ACA  /* race, u8 */
#define DS_cpu_speed                                 0x8ACC  /* platform, u16 */
#define DS_opp_sprites                               0x8ACE  /* race, Pic far*[13] */
#define DS_anim_engine_ref                           0x8B7C  /* sound, s16 */
#define DS_pic_mirror_sky                            0x8B7E  /* race, Pic far* */
#define DS_centre_ptr                                0x8B82  /* race, far u16* */
#define DS_opp_alongside                             0x8BC2  /* race, u16 */
#define DS_race_time                                 0x8BC4  /* race, float */
#define DS_lib1_count                                0x8BC8  /* platform, u16 */
#define DS_pic_hood                                  0x8BCA  /* race, Pic far* */
#define DS_demo_switch                               0x8BCE  /* platform, u16 */
#define DS_edge_right                                0x8BD0  /* race, s16 */
#define DS_lib2_count                                0x8DD2  /* platform, u16 */
#define DS_lib1_name                                 0x8DD4  /* platform, char * */
#define DS_lib2_name                                 0x8DD6  /* platform, char * */
#define DS_MODEL_PICS                                0x8DF0  /* garage, u8[26][10] */
#define DS_tq_default_prio                           0x8EF6  /* platform, u16 */

/* ---- Code-segment globals (CS_x offset, CSSEG_x file segment) */
#define CS_track_left                                0x33F0  /* race, u16[0x460] */
#define CSSEG_track_left                             0x389B
#define CS_track_right                               0x3CB0  /* race, u16[0x460] */
#define CSSEG_track_right                            0x389B
#define CS_track_yaw                                 0x4570  /* race, s16[0x460] */
#define CSSEG_track_yaw                              0x389B
#define CS_track_centre                              0x4E30  /* race, u16[0x460] */
#define CSSEG_track_centre                           0x389B
#define CS_track_height                              0x56F0  /* race, s16[0x460] */
#define CSSEG_track_height                           0x389B

/* ---- Original functions (file segment << 16 | offset) */
#define FN_dos_print_line                            0x00000000u  /* platform, near void (char *s) */
#define FN_video_menu                                0x00000082u  /* platform, near int (int recommended) */
#define FN_vga_detect                                0x0000018Bu  /* platform, near int (void) */
#define FN_bios_set_mode                             0x000001D1u  /* platform, far void (int mode) */
#define FN_cga_set_palette                           0x000001F2u  /* platform, far void (int pal) */
#define FN_video_detect_menu                         0x00000226u  /* platform, near int (void) */
#define FN_driver_select                             0x00000316u  /* platform, near void (int mode) */
#define FN_video_mode_set                            0x000004F4u  /* platform, near void (int mode) */
#define FN_cpu_speed_calibrate                       0x000005C6u  /* platform, near int (void) */
#define FN_slow_flag_set                             0x00000659u  /* platform, near void (void) */
#define FN_main                                      0x0000066Fu  /* platform, far void (int argc; char **argv) */
#define FN_classifieds_open                          0x000008B4u  /* garage, void(int *list, int item) */
#define FN_classifieds_pic                           0x000009B7u  /* garage, Desc far *(int pool) */
#define FN_classifieds_run                           0x000009CBu  /* garage, int(void) */
#define FN_hotspots_reset                            0x00000D58u  /* platform, far void (void) */
#define FN_click_clear                               0x00000D78u  /* platform, far void (void) */
#define FN_music_stop                                0x00000D99u  /* platform, far void (void) */
#define FN_music_resume                              0x00000DD8u  /* platform, far void (void) */
#define FN_input_reset                               0x00000E24u  /* platform, far void (void) */
#define FN_tq_remove                                 0x00000F0Bu  /* platform, far void (int e) */
#define FN_timer_restore                             0x00000FB7u  /* platform, far void (void) */
#define FN_platform_exit                             0x00000FEAu  /* platform, far noreturn (void) */
#define FN_crit_err_handler                          0x0000105Bu  /* platform, far void (u16 deverror; u16 errcode; void far *d */
#define FN_platform_install                          0x00001111u  /* platform, far void (void) */
#define FN_kbd_remap_screen                          0x000012DEu  /* platform, far void (int screen) */
#define FN_kbd_remap_restore                         0x00001391u  /* platform, far int (int keep_low) */
#define FN_ui_wait                                   0x00001417u  /* platform, far int (int ticks) */
#define FN_tq_insert                                 0x00001843u  /* platform, far int (int delay; int prio) */
#define FN_tq_schedule_call                          0x0000198Au  /* platform, far void (int arg; int delay) */
#define FN_tq_cancel_call                            0x000019BCu  /* platform, far void (int arg) */
#define FN_tune_start                                0x00001A05u  /* platform, far void (int tune; int repeat) */
#define FN_tune_rewind                               0x00001A7Cu  /* platform, far void (void) */
#define FN_race_isr_enter                            0x00001AADu  /* platform, far void (void) */
#define FN_race_isr_leave                            0x00001B27u  /* platform, far void (void) */
#define FN_sign_0000_1B91                            0x00001B91u  /* platform, far int (int v) */
#define FN_demo_step                                 0x00001BAEu  /* platform, far void (void) */
#define FN_timer_isr                                 0x00001FE2u  /* platform, interrupt */
#define FN_race_ctrl_reset                           0x00002374u  /* platform, far void (void) */
#define FN_race_isr                                  0x0000238Cu  /* platform, interrupt */
#define FN_race_phys_step                            0x0000253Bu  /* race, far void() */
#define FN_bios_mode_a_set                           0x00002B9Au  /* platform, far void (u8 equip; u8 mode) */
#define FN_bios_mode_b_set                           0x00002BADu  /* platform, far void (u8 equip; u8 mode) */
#define FN_bios_mode_a_apply                         0x00002BC0u  /* platform, far void (void) */
#define FN_bios_mode_b_apply                         0x00002BE2u  /* platform, far void (void) */
#define FN_kbd_text_mode_on                          0x00002C04u  /* platform, far void (int keep_space) */
#define FN_kbd_text_mode_off                         0x00002C2Bu  /* platform, far void (void) */
#define FN_kbd_isr                                   0x00002C42u  /* platform, interrupt */
#define FN_key_read                                  0x00002DB6u  /* platform, far int (void) */
#define FN_kbd_install                               0x00002DC3u  /* platform, far void (void) */
#define FN_kbd_restore                               0x00002DE2u  /* platform, far void (void) */
#define FN_joy_read                                  0x00002DF4u  /* platform, far void (void) */
#define FN_kbd_inject_scancode                       0x00002E93u  /* game_flow, void far (void) */
#define FN_copy_protection                           0x00002FC8u  /* game_flow, int far (void) */
#define FN_game_over_menu                            0x0000315Bu  /* game_flow, int far (void) */
#define FN_hall_is_slower                            0x000032D0u  /* game_flow, bool near (int i) */
#define FN_hall_insert                               0x000032F4u  /* game_flow, void near (int i) */
#define FN_hall_score                                0x00003375u  /* game_flow, int near (void) */
#define FN_hall_of_fame_screen                       0x0000339Fu  /* game_flow, void far (int won) */
#define FN_pools_init                                0x00003614u  /* game_flow, void near (int full) */
#define FN_get_ds                                    0x000036A8u  /* platform, far u16 (void) */
#define FN_mem_pools_init                            0x000036BEu  /* platform, near void (void) */
#define FN_far_free                                  0x000036D6u  /* platform, far void (void far *p) */
#define FN_out_of_memory                             0x000036E9u  /* platform, far noreturn (void) */
#define FN_far_alloc                                 0x00003709u  /* platform, far void far *(u16 size; int fatal) */
#define FN_bitmap_alloc                              0x0000376Bu  /* platform, far Bitmap far *(int w; int h; int flags; int dr */
#define FN_bitmap_make                               0x00003880u  /* platform, far Bitmap far *(void far *data; void far *mask; */
#define FN_bitmap_init                               0x00003904u  /* platform, far void (Bitmap far *d; void far *data; void fa */
#define FN_vram_pool_alloc                           0x00003967u  /* platform, far void far *(u16 size; u8 *plane) */
#define FN_title_and_setup                           0x000039C0u  /* game_flow, int near (void) */
#define FN_wait_ticks                                0x00003A83u  /* game_flow, void far (int n) */
#define FN_msg_box                                   0x00003AB8u  /* game_flow, void far (int id) */
#define FN_garage_full_check                         0x00003B0Cu  /* game_flow, int near (void) */
#define FN_newspaper_front                           0x00003B33u  /* game_flow, int near (void) */
#define FN_part_alloc                                0x00003C1Bu  /* game_flow, u16 near (void) */
#define FN_part_free                                 0x00003C3Eu  /* game_flow, void near (u16 p) */
#define FN_part_value                                0x00003C5Au  /* garage, far int(PART*) */
#define FN_sell_spare_parts                          0x00003C8Du  /* garage, void(void) */
#define FN_car_alloc                                 0x00003FB1u  /* garage, CAR*(void) */
#define FN_car_release                               0x00003FD4u  /* garage, void(CAR*) */
#define FN_spare_add                                 0x00003FF0u  /* garage, void(int type, int value) */
#define FN_car_new                                   0x00004036u  /* garage, CAR*(int model, int value, CAR *reuse) */
#define FN_part_release                              0x00004386u  /* garage, int(PART*, int keep) */
#define FN_car_free                                  0x000043BFu  /* garage, int(CAR*, int keep) */
#define FN_classifieds                               0x0000442Bu  /* garage, void(int section) */
#define FN_how_about                                 0x00004940u  /* garage, int(uint *offer) */
#define FN_car_flags                                 0x000049A2u  /* garage, far uint(CAR*) */
#define FN_your_cars                                 0x000049EDu  /* garage, int(void) */
#define FN_sfx_play_wait                             0x00004FCAu  /* garage, far void(int n) */
#define FN_message_at                                0x00004FFAu  /* garage, far void(int id, int x, int y) */
#define FN_game_loop                                 0x0000503Fu  /* game_flow, void near (void) */
#define FN_opponent_init                             0x0000542Eu  /* garage, far void(int i, int *pool) */
#define FN_opponents_init                            0x00005584u  /* garage, void(void) */
#define FN_new_game                                  0x000056A9u  /* garage, void(void) */
#define FN_new_game_prompt                           0x0000570Cu  /* garage, int(void) */
#define FN_save_part_chain                           0x00005795u  /* game_flow, int near (int fd u16 p) */
#define FN_load_part_chain                           0x000057DCu  /* game_flow, int near (int fd u16 *head) */
#define FN_save_car_chain                            0x0000586Eu  /* game_flow, int near (int fd u16 car int one) */
#define FN_load_car_chain                            0x0000590Fu  /* game_flow, int near (int fd u16 *head int one) */
#define FN_save_slots_scan                           0x000059F6u  /* game_flow, void near (int for_save) */
#define FN_load_game_screen                          0x00005B4Au  /* game_flow, int near (void) */
#define FN_str_is_blank                              0x00005EB3u  /* game_flow, int near (char *s) */
#define FN_save_game_screen                          0x00005EEAu  /* game_flow, void near (void) */
#define FN_quit_menu                                 0x0000641Eu  /* game_flow, int near (void) */
#define FN_day_index                                 0x00006476u  /* garage, far int(void) */
#define FN_clock_hm                                  0x000064A3u  /* garage, far void(int *h, int *m) */
#define FN_summer_over_check                         0x00006529u  /* garage, far void(void) */
#define FN_month_of_day                              0x0000653Cu  /* garage, int(int day, int *dom) */
#define FN_calendar_show                             0x000065AFu  /* garage, far void(int quick) */
#define FN_date_print                                0x00006750u  /* garage, far void(int y) */
#define FN_set_paint_palette                         0x000067CFu  /* garage, far void(int colour) */
#define FN_hotspot_find                              0x00006827u  /* garage, far int(int code) */
#define FN_garage_hotspots_register                  0x00006882u  /* garage, void(void) */
#define FN_garage_hotspots_nocar                     0x000068B3u  /* garage, void(void) */
#define FN_garage_hotspots_car                       0x000068E8u  /* garage, void(int model, int x, int y) */
#define FN_garage_name_clear                         0x00006AA6u  /* garage, far void(void) */
#define FN_broke_check                               0x00006AD8u  /* garage, int(void) */
#define FN_garage_screen                             0x00006B06u  /* garage, int(int mode) */
#define FN_paint_job                                 0x00006F6Bu  /* garage, void(void) */
#define FN_customize                                 0x0000711Au  /* garage, void(int what) */
#define FN_stickers                                  0x00007367u  /* garage, void(void) */
#define FN_spares_collect                            0x000076A7u  /* garage, void(int cat, PART **nodes, char *wear, int n0) */
#define FN_part_install                              0x00007741u  /* garage, void(PART *p, PART **slot) */
#define FN_part_uninstall                            0x00007789u  /* garage, void(PART **slot) */
#define FN_spare_unlink                              0x000077B7u  /* garage, PART*(PART *p) */
#define FN_change_tires                              0x00007800u  /* garage, void(void) */
#define FN_car_info_list                             0x000078F1u  /* garage, void(int *xoff, char *wear) */
#define FN_car_info                                  0x000079EBu  /* garage, far void(void) */
#define FN_change_transmission                       0x00007AA4u  /* garage, void(void) */
#define FN_car_runnable                              0x00007EE6u  /* garage, far int(CAR*, int full) */
#define FN_ignition_tune                             0x00007FB1u  /* garage, void(CAR*) */
#define FN_engine_bay                                0x000081ABu  /* garage, void(CAR*) */
#define FN_drive_to                                  0x00008D26u  /* race, far void() */
#define FN_opp_palette_set                           0x00008D9Cu  /* race, far void(int) */
#define FN_drive_run                                 0x00008E2Du  /* race, far int() */
#define FN_race_logic                                0x00008EA8u  /* race, far uint() */
#define FN_waitress_toggle                           0x0000914Cu  /* race, near int(int;int;int;int) */
#define FN_str_drop_last_word                        0x00009256u  /* race, near void(char*) */
#define FN_opponent_show                             0x000092A4u  /* race, near void(int;...) */
#define FN_model_class3                              0x00009524u  /* race, near int(int) */
#define FN_king_status                               0x00009556u  /* race, near int() */
#define FN_king_chance                               0x000095F1u  /* race, near int() */
#define FN_opp_sort                                  0x00009646u  /* race, near void(int) */
#define FN_pick_opponent                             0x0000984Eu  /* race, near int(int;int) */
#define FN_opponent_load                             0x000098BAu  /* race, near void(int) */
#define FN_opponent_select                           0x00009A27u  /* race, near void(int;int;int) */
#define FN_opp_known_list                            0x00009A83u  /* race, near void(int*;int*;int*) */
#define FN_opponent_search                           0x00009AF4u  /* race, near int(int) */
#define FN_challenge_accept                          0x00009BC5u  /* race, near int(int) */
#define FN_challenge                                 0x00009D6Du  /* race, near int(int) */
#define FN_bob_hotspots                              0x0000A0F8u  /* race, near void(int;int) */
#define FN_opponent_car_view                         0x0000A265u  /* race, near void() */
#define FN_girl_frame                                0x0000A35Cu  /* race, near void(...) */
#define FN_dancing_girl                              0x0000A416u  /* race, near void() */
#define FN_ending_king                               0x0000A544u  /* race, near void() */
#define FN_bob_drive_in                              0x0000AB8Bu  /* race, far void() */
#define FN_jail_hotspots                             0x0000B045u  /* race, near void(int;byte) */
#define FN_jail                                      0x0000B08Cu  /* race, far void() */
#define FN_gas_hotspot_find                          0x0000B3CAu  /* race, near int(int) */
#define FN_gas_hotspots_apply                        0x0000B425u  /* race, near void() */
#define FN_gas_hotspots_clear                        0x0000B456u  /* race, near void() */
#define FN_gas_hotspot_set                           0x0000B49Cu  /* race, near void(int;int;int;int;int) */
#define FN_gas_hotspots_a                            0x0000B4DEu  /* race, near void() */
#define FN_gas_hotspots_b                            0x0000B525u  /* race, near void() */
#define FN_gas_hotspots_c                            0x0000B552u  /* race, near void() */
#define FN_gas_hotspots_d                            0x0000B59Bu  /* race, near void() */
#define FN_gas_hotspots_none                         0x0000B617u  /* race, near void() */
#define FN_gas_draw_pump                             0x0000B61Bu  /* race, near void(void*;int) */
#define FN_gas_leave                                 0x0000B717u  /* race, near void(void*) */
#define FN_gas_station                               0x0000B8A1u  /* race, far void() */
#define FN_tires_replace                             0x0000BED4u  /* race, near int() */
#define FN_ticket_show                               0x0000BF94u  /* race, near void() */
#define FN_crash_show                                0x0000C1D8u  /* race, near void() */
#define FN_finish_stats                              0x0000C407u  /* race, far void() */
#define FN_race_msg                                  0x0000C497u  /* race, near void() */
#define FN_engine_blown                              0x0000C52Cu  /* race, near void(int) */
#define FN_trans_blown                               0x0000C5ACu  /* race, near void(int) */
#define FN_race_results                              0x0000C613u  /* race, near uint() */
#define FN_phys_reset                                0x0000CDAFu  /* race, near void(phys*) */
#define FN_opponent_setup                            0x0000CF5Cu  /* race, near void() */
#define FN_race_start                                0x0000D031u  /* race, near void() */
#define FN_opp_gear                                  0x0000D1DEu  /* race, near void(int;phys*) */
#define FN_opp_ai                                    0x0000D29Du  /* race, near void() */
#define FN_speed_to_step                             0x0000D544u  /* race, far int(int) */
#define FN_player_advance                            0x0000D624u  /* race, near void() */
#define FN_opp_advance_steer                         0x0000D67Du  /* race, near void() */
#define FN_police_spawn                              0x0000D992u  /* race, near void() */
#define FN_race_step                                 0x0000DA25u  /* race, far void() */
#define FN_car_setup                                 0x0000DCBEu  /* race, near void(car*;phys*) */
#define FN_model_car_setup                           0x0000E0E2u  /* race, near void(int;phys*) */
#define FN_car_max_speed                             0x0000E218u  /* race, near int(int) */
#define FN_herc_mem_alias                            0x0000E56Au  /* platform, far bool (void) */
#define FN_herc_detect                               0x0000E584u  /* platform, far bool (void) */
#define FN_equip_is_mono                             0x0000E5C3u  /* platform, far int (void) */
#define FN_herc_graphics_on                          0x0000E5D2u  /* platform, near void (void) */
#define FN_video_restore                             0x0000E610u  /* platform, far void (void) */
#define FN_ega_vga_detect                            0x0000E62Fu  /* platform, near void (void) */
#define FN_tdy_draw_cursor                           0x0E6C0002u  /* video */
#define FN_ega_draw_cursor                           0x0E6C0175u  /* video, far void (u8 far *img; u8 far *mask; u8 far *sav */
#define FN_pic_unpack                                0x0E920006u  /* video, far int (u8 far *src; u8 far *dst; int n; u8 *to */
#define FN_dash_restore_rect                         0x0F38000Au  /* race, near void(int;int;int;int;int) */
#define FN_dash_copy_rect                            0x0F380098u  /* race, near void(int;int;int;int;int) */
#define FN_speedo_points                             0x0F380137u  /* race, far void(int;int*;int*;int*;int*) */
#define FN_speedo_init                               0x0F3801D2u  /* race, far void(int) */
#define FN_tach_points                               0x0F3802AEu  /* race, far void(int;int*;int*;int*;int*) */
#define FN_tach_init                                 0x0F380349u  /* race, far void(int) */
#define FN_needle_update                             0x0F380425u  /* race, far int(int;int;int) */
#define FN_clock_draw                                0x0F3805F2u  /* race, far void() */
#define FN_pal_black                                 0x0F380B2Du  /* video, far void (void) */
#define FN_pal_normal                                0x0F380B3Fu  /* video, far void (void) */
#define FN_wait_click_or_key                         0x0F380B51u  /* platform, far void (int ticks) */
#define FN_title_sequence                            0x0F380BF0u  /* game_flow, void far (void) */
#define FN_summer_over_screen                        0x0F380D62u  /* game_flow, void far (void) */
#define FN_gfx_screen_mode                           0x0F380DBDu  /* video, far void (int n) */
#define FN_wheel_load                                0x0F380F53u  /* race, far void() */
#define FN_wheel_knob_crash                          0x0F381094u  /* race, far void(int) */
#define FN_wheel_draw                                0x0F381130u  /* race, far void(int;int;far*) */
#define FN_shifter_draw                              0x0F3812F7u  /* race, far void(int;int) */
#define FN_shifter_knob                              0x0F3814F2u  /* race, far void(far*;phys*) */
#define FN_far_memset                                0x0F381640u  /* video, far void (u8 far *p; u8 v; u16 n) */
#define FN_clip_rect                                 0x0F381680u  /* video, far int (Desc far *s; Desc far *d; Rect *in; Rec */
#define FN_wait_vretraces                            0x0F38177Du  /* video, far void (int n) */
#define FN_font_string_width                         0x0F3817C8u  /* video, far int (char *s) */
#define FN_pal_reg12_5                               0x0F3817FCu  /* video, far void (void) */
#define FN_pal_reg12_13                              0x0F38180Cu  /* video, far void (void) */
#define FN_pal_shadow_patch                          0x0F38181Cu  /* video, far void (void) */
#define FN_pal_shadow_swap                           0x0F38182Cu  /* video, far void (void) */
#define FN_gfx_init                                  0x0F381859u  /* video, far void (Desc far *a; Desc far *b) */
#define FN_anim_stop                                 0x0F3819ECu  /* garage, void(int id) */
#define FN_anim_set_params                           0x0F381A5Fu  /* garage, void(void) */
#define FN_anim_run                                  0x0F381ABDu  /* garage, void(int slot) */
#define FN_anim_start                                0x0F381DC9u  /* garage, int(int id) */
#define FN_anim_tick                                 0x0F381E41u  /* garage, void(int id) */
#define FN_anim_active                               0x0F381E72u  /* garage, int(int id) */
#define FN_anim_blink_led                            0x0F381E93u  /* garage, int(Anim *a, Step *p) */
#define FN_ega_set_palreg                            0x0F381F4Bu  /* video, far void (int reg; int colour) */
#define FN_ega_set_palette                           0x0F381FA4u  /* video, far void (u8 *pal16) */
#define FN_status_init                               0x0F382022u  /* video, far void (int y) */
#define FN_status_print                              0x0F3820A1u  /* video, far void (int x; char *s; int w) */
#define FN_money_add                                 0x0F3821C0u  /* race, far void(int) */
#define FN_status_label                              0x0F382213u  /* video, far void (char *s) */
#define FN_gear_label                                0x0F3822E9u  /* race, far void(int) */
#define FN_screen_fill_rect                          0x0F38231Au  /* video, far void (int x; int y; int w; int h; u8 c) */
#define FN_dialog_msg                                0x0F38239Cu  /* garage, void(char *s) */
#define FN_fatal_message                             0x0F3823CEu  /* garage, void(char *s) */
#define FN_show_picture                              0x0F382554u  /* video, far void (int id; int clr) */
#define FN_show_picture_at                           0x0F382638u  /* video, far void (int id; int x; int y; int clr) */
#define FN_screen_text                               0x0F382656u  /* video, far void (int x; int y; char *s) */
#define FN_screen_hline                              0x0F3826A4u  /* video, far void (int x; int y; int w) */
#define FN_screen_save_rect                          0x0F3826F2u  /* video, far Desc far *(int x; int y; int w; int h; Desc  */
#define FN_screen_put_bitmap                         0x0F3827EFu  /* video, far void (Desc far *b; int x; int y) */
#define FN_screen_put_bitmap_mirror                  0x0F382853u  /* video, far void (Desc far *b; int x; int y) */
#define FN_msg_draw                                  0x0F3828A4u  /* garage, void(int id) */
#define FN_msg_draw_at                               0x0F382A62u  /* garage, void(int id, int x, int y) */
#define FN_msg_erase                                 0x0F382ADFu  /* garage, void(void) */
#define FN_cursor_shape_offset                       0x0F382B1Cu  /* video, far u16 (int n) */
#define FN_cursor_init                               0x0F382B28u  /* video, far void (void) */
#define FN_cursor_ctl                                0x0F382D7Eu  /* video, far void (int op) */
#define FN_cursor_redraw                             0x0F382E8Bu  /* video, far void (int x; int y) */
#define FN_trans_bolt_draw                           0x0F383074u  /* garage, void(int tight, int bolt) */
#define FN_trans_bolt_remove_anim                    0x0F3831A5u  /* garage, void(int bolt) */
#define FN_trans_slide_anim                          0x0F3832CEu  /* garage, void(int pic, int reject) */
#define FN_trans_remove_anim                         0x0F383404u  /* garage, void(int pic, int mode) */
#define FN_trans_screen_draw                         0x0F38345Bu  /* garage, void(int pic, char *bolts, ...) */
#define FN_bay_engine_idx                            0x0F3834FBu  /* garage, int(void) */
#define FN_bay_carb_pos                              0x0F38351Cu  /* garage, int(int *x, int *y) */
#define FN_bay_part_pos                              0x0F383589u  /* garage, void(int *x, int *y) */
#define FN_bay_bolt_pos                              0x0F3835E4u  /* garage, void(int *x, int *y) */
#define FN_bay_bolt_draw                             0x0F383697u  /* garage, void(int pic) */
#define FN_bay_bolt_remove_anim                      0x0F3837FCu  /* garage, void(void) */
#define FN_bay_carb_overlay                          0x0F383951u  /* garage, void(void) */
#define FN_bay_part_in_anim                          0x0F383A58u  /* garage, void(int pic, int reject) */
#define FN_bay_part_out_anim                         0x0F383C19u  /* garage, void(int pic, int mode) */
#define FN_bay_connector_draw                        0x0F383D1Cu  /* garage, void(void) */
#define FN_bay_draw_car                              0x0F383E35u  /* garage, void(CAR*) */
#define FN_bay_draw_parts                            0x0F383F2Du  /* garage, void(int *tbl, int *bolts, int own) */
#define FN_hot_insert                                0x0F38404Bu  /* garage, void(rec *base, rec *r, int n) */
#define FN_bay_draw_bolts                            0x0F3840CAu  /* garage, void(int *tbl, int *bolts) */
#define FN_ui_sort_records                           0x0F384265u  /* garage, void(int first, int n) */
#define FN_fill_rect                                 0x0F384302u  /* video, far void (Desc far *d; int x; int y; int w; int  */
#define FN_vline                                     0x0F38439Cu  /* video, far void (Desc far *d; int x; int y; int h) */
#define FN_hline                                     0x0F3843FFu  /* video, far void (Desc far *d; int x; int y; int w) */
#define FN_draw_frame3                               0x0F384432u  /* video, far void (Desc far *d; int x; int y; int w; int  */
#define FN_draw_box1                                 0x0F3845D7u  /* video, far void (Desc far *d; int x; int y; int w; int  */
#define FN_ui_draw_records                           0x0F38465Eu  /* garage, void(rec*) */
#define FN_ui_push                                   0x0F384A66u  /* garage, void(int screen) */
#define FN_ui_pop                                    0x0F384BA1u  /* garage, void(int redraw) */
#define FN_ui_state_reset                            0x0F384BFFu  /* garage, void(void) */
#define FN_ui_bounds                                 0x0F384C1Au  /* garage, void(int screen, int *x, int *y, int *w, int *h) */
#define FN_ui_save_bg                                0x0F384D10u  /* garage, Desc far *(int screen, int *x, int *y, int pool) */
#define FN_hotspot_at                                0x0F384DADu  /* garage, int(int x, int y) */
#define FN_ui_dialog                                 0x0F384EC1u  /* garage, int(int screen) */
#define FN_ui_menu                                   0x0F384F14u  /* garage, int(int screen) */
#define FN_list_box                                  0x0F384F4Fu  /* garage, far int(int scr, int sel, int *xoff, int *list,  */
#define FN_wear_text                                 0x0F384FC1u  /* garage, char*(int pct) */
#define FN_list_box_run                              0x0F38500Eu  /* garage, far int(...) */
#define FN_list_selected                             0x0F38590Bu  /* garage, far int(void) */
#define FN_text_input                                0x0F385910u  /* garage, int(int x, int y, char *buf, int maxlen) */
#define FN_prompt_number                             0x0F385D37u  /* garage, int(int x, int y, char *label, uint *v) */
#define FN_edit_number                               0x0F385DA7u  /* garage, far int(uint *v, char *buf) */
#define FN_ui_edit_number                            0x0F385E1Eu  /* garage, int(int screen, uint *v) */
#define FN_ui_edit                                   0x0F385E54u  /* garage, int(int screen, int maxlen, char *buf) */
#define FN_rnd                                       0x0F385EB6u  /* platform, far int (int n) */
#define FN_lib_seek                                  0x0F386016u  /* platform, far int (int handle; long pos) */
#define FN_pic_index                                 0x0F386057u  /* platform, near int (int id) */
#define FN_lib_select                                0x0F386089u  /* platform, near void (int id) */
#define FN_lib_read_dir                              0x0F3861ABu  /* platform, far int (int lib) */
#define FN_pic_load                                  0x0F3862BAu  /* platform, near int (int id; int to_vram; void far *dst) */
#define FN_pic_free                                  0x0F38655Eu  /* platform, far void (int id) */
#define FN_pic_decode                                0x0F3865AEu  /* platform, far Bitmap far *(int id; Bitmap far *dst) */
#define FN_pic_info                                  0x0F3867FFu  /* platform, far void (int id; int *w; int *h; int *masked) */
#define FN_pic_get                                   0x0F38683Eu  /* platform, far Bitmap far *(int id; int mode) */
#define FN_pic_park_list                             0x0F386887u  /* platform, far int (int *ids) */
#define FN_pic_load_list                             0x0F3868CAu  /* platform, far int (int *ids; int keep_going) */
#define FN_pic_free_list                             0x0F386915u  /* platform, far void (int *ids) */
#define FN_lib_open_all                              0x0F386943u  /* platform, far void (int disks; int mode) */
#define FN_hot_data_load                             0x0F386B79u  /* platform, far void (void) */
#define FN_data_disk_check                           0x0F386C3Du  /* platform, far int (void) */
#define FN_hall_scramble                             0x0F386CCFu  /* platform, near void (void) */
#define FN_hall_unscramble                           0x0F386CECu  /* platform, near void (void) */
#define FN_hall_load                                 0x0F386D09u  /* platform, far void (void) */
#define FN_hall_save                                 0x0F386DD2u  /* platform, far void (void) */
#define FN_song_select                               0x0F386F0Au  /* sound, void far (u16 off, u16 seg, u16 loop_tbl) */
#define FN_vib_set                                   0x0F386FBDu  /* sound, void far (int on, int row, int period, int depth */
#define FN_music_off_rewind                          0x0F386FECu  /* sound, void far (void) */
#define FN_music_mute                                0x0F387001u  /* sound, void far (int mute) */
#define FN_snd_calibrate_delay                       0x0F38703Eu  /* sound, int far (int n) */
#define FN_spk_set_hz                                0x0F3870D5u  /* sound, void far (long hz) */
#define FN_snd_init                                  0x0F387101u  /* sound, void far (void) */
#define FN_spk_on                                    0x0F387122u  /* sound, void far (void) */
#define FN_spk_off                                   0x0F38713Du  /* sound, void far (void) */
#define FN_fx_tone                                   0x0F38714Cu  /* sound, void near (long hz, int d) */
#define FN_fx_burst                                  0x0F387169u  /* sound, void near (int lo, int hi, int d, int n) */
#define FN_fx_sweep_down                             0x0F3871B2u  /* sound, void near (int from, int to, int step, int d) */
#define FN_fx_warble                                 0x0F3871E4u  /* sound, void near (int c, int dev, int step, int d, int  */
#define FN_pwm_up                                    0x0F387292u  /* sound, void near (int period, int *duty, int n, int rep */
#define FN_pwm_down                                  0x0F387306u  /* sound, void near (int period, int *duty, int n, int rep */
#define FN_ramp_fill                                 0x0F38737Au  /* sound, int near (int *buf, int from, int to, int step) */
#define FN_pwm_swell                                 0x0F3873EDu  /* sound, void near (long hz, int period, int to, int step */
#define FN_fx_noise                                  0x0F387464u  /* sound, void near (int range, int ormask, int n) */
#define FN_fx_noise_down                             0x0F3874B0u  /* sound, void near (int a, int b, int sub, int step, int  */
#define FN_fx_noise_up                               0x0F3874FCu  /* sound, void near (int a, int b, int sub, int step, int  */
#define FN_loop_idle_putt                            0x0F387548u  /* sound, void far (int on) */
#define FN_loop_spray                                0x0F387573u  /* sound, void far (int on) */
#define FN_loop_hum100                               0x0F3875C3u  /* sound, void far (int on) */
#define FN_loop_tick                                 0x0F387613u  /* sound, void far (int on) */
#define FN_loop_crank                                0x0F387661u  /* sound, void far (int on) */
#define FN_loop_rumble                               0x0F3876AFu  /* sound, void far (int on) */
#define FN_loop_wrench                               0x0F3876DAu  /* sound, void far (int on) */
#define FN_siren_set                                 0x0F387728u  /* sound, void far (int on) */
#define FN_squeal_set                                0x0F387741u  /* sound, void far (int on) */
#define FN_fx_pwm_a                                  0x0F38775Au  /* sound, void far (void) */
#define FN_fx_pwm_b                                  0x0F38778Au  /* sound, void far (void) */
#define FN_fx_click                                  0x0F3877BAu  /* sound, void far (void) */
#define FN_fx_chirp_hi                               0x0F3877E1u  /* sound, void far (void) */
#define FN_fx_chirp_lo                               0x0F387817u  /* sound, void far (void) */
#define FN_fx_clank                                  0x0F387841u  /* sound, void far (void) */
#define FN_fx_crash                                  0x0F387863u  /* sound, void far (void) */
#define FN_fx_hit                                    0x0F38790Fu  /* sound, void far (void) */
#define FN_fx_thud                                   0x0F387973u  /* sound, void far (void) */
#define FN_mouse_reset                               0x0F38799Au  /* platform, far int (void) */
#define FN_mouse_buttons                             0x0F3879D7u  /* platform, far void (void) */
#define FN_mouse_motion                              0x0F387A14u  /* platform, far void (int *dx; int *dy) */
#define FN_mouse_poll                                0x0F387A47u  /* platform, far void (void) */
#define FN_race_run                                  0x0F387B22u  /* race, far int() */
#define FN_ega_blit_4planes                          0x0F388126u  /* video, near */
#define FN_ega_vram_cache_strips                     0x0F38819Au  /* video, near */
#define FN_car_strip_setup                           0x0F3884BEu  /* garage, void(Desc far *bg, Desc far **bgsrc, int smoke,  */
#define FN_pump_overlay                              0x0F38872Eu  /* garage, void(int x, int dy, int carx, int y, Desc far *d */
#define FN_car_compose                               0x0F388866u  /* garage, far void(...) */
#define FN_car_draw                                  0x0F388E48u  /* garage, far void(int mode, int model, int flags, int sti */
#define FN_walker_anim                               0x0F38975Bu  /* garage, void(Desc far *pic, int sx, int sy, int w, int h */
#define FN_carhop_frames                             0x0F38985Cu  /* garage, void(Desc far **frames, int mode) */
#define FN_carhop_strip                              0x0F38990Fu  /* garage, void(Desc far **d) */
#define FN_carhop_anim                               0x0F3899D9u  /* garage, void(int mode, int opp) */
#define FN_town_bg_save                              0x0F389E5Du  /* garage, void(void) */
#define FN_arena_clear                               0x0F389EBCu  /* platform, far void (void) */
#define FN_arena_init                                0x0F389EE9u  /* platform, far void (void) */
#define FN_arena_low_shrink                          0x0F389F1Au  /* platform, far void (int n) */
#define FN_arena_alloc                               0x0F389F2Cu  /* platform, far void far *(int n; int mode) */
#define FN_arena_bitmap_alloc                        0x0F389FCEu  /* video, far Desc far *(int w; int h; int flags; int pool */
#define FN_arena_reset                               0x0F38A054u  /* platform, far void (void) */
#define FN_arena_reset_stacks                        0x0F38A07Eu  /* platform, far void (void) */
#define FN_arena_pop_low                             0x0F38A09Eu  /* platform, far void (int n) */
#define FN_arena_pop                                 0x0F38A0B8u  /* platform, far void (int k) */
#define FN_rect_intersect                            0x0F38A0FAu  /* video, far i16 *(i16 *a; i16 *b; i16 *out) */
#define FN_rect_clip_to_view                         0x0F38A198u  /* video, far i16 *(int x; int y; int w; int h; i16 *out) */
#define FN_rect_clip_make                            0x0F38A1EEu  /* video, far void (int w; int h; int x; int y; int maxw;  */
#define FN_sprite_scene_setup                        0x0F38A273u  /* video, far void *(...) */
#define FN_rect_subtract_edge                        0x0F38A4B9u  /* video, far i16 *(i16 *a; i16 *b; i16 *out; int horiz) */
#define FN_anim_ring_reverse                         0x0F38A5A5u  /* garage, void(Anim *a) */
#define FN_anim_phase_set                            0x0F38A65Du  /* garage, void(Anim *a, int i, int count, int dx, int dy) */
#define FN_anim_phases                               0x0F38A6ADu  /* garage, void(Anim *a, int mode, int d1, int d2, int d3,  */
#define FN_anim_script                               0x0F38A7EEu  /* garage, void(Anim *a, int mode, int dist) */
#define FN_sprite_anim_advance                       0x0F38AA37u  /* video, far void (Anim *a) */
#define FN_sprite_hspan_clip                         0x0F38AAC2u  /* video, far int (int x; int w; Anim *a; i16 *out) */
#define FN_bitmap_copy_into                          0x0F38AB50u  /* video, far void (Desc far *s; Desc far *d; int flags) */
#define FN_bitmap_opaque_extent                      0x0F38ABC2u  /* video, far void (Desc far *b; int *left; int *right) */
#define FN_bitmap_make_shifted                       0x0F38ACBFu  /* video, far Desc far *(Desc far *s; int shift; Desc far  */
#define FN_bitmap_blit_masked_shift                  0x0F38AF50u  /* video, far void (Desc far *s; Desc far *d; i16 *r; int  */
#define FN_bitmap_composite_behind                   0x0F38B0F2u  /* video, far void (Desc far *s; Desc far *d; int x; int y */
#define FN_bitmap_blit_at                            0x0F38B31Fu  /* video, far void (Desc far *s; Desc far *d; int dx; int  */
#define FN_pic_blit_at                               0x0F38B360u  /* video, far void (Desc far *d; int id; u8 x; u8 y) */
#define FN_pic_draw_masked                           0x0F38B3B4u  /* video, far void (Desc far *d; int id; u8 x; u8 y; int f */
#define FN_mask_and_rect                             0x0F38B41Bu  /* video, far void (Desc far *s; Desc far *d; Rect *r) */
#define FN_far_memcpy                                0x0F38B502u  /* video, far void (void far *src; void far *dst; u16 n) */
#define FN_bitmap_extract                            0x0F38B51Eu  /* video, far Desc far *(Desc far *s; i16 *r; int pool) */
#define FN_page_copy_rect                            0x0F38B5AAu  /* video, far void (Desc far *s; Desc far *d; int x0; int  */
#define FN_tc_wheel_strip                            0x0F38B632u  /* garage, Desc far *(int x) */
#define FN_tc_wheel_swap                             0x0F38B82Cu  /* garage, void(int x, int *old, int *new) */
#define FN_tire_change_anim                          0x0F38BE93u  /* garage, far void(int *old_pics, int *new_pics) */
#define FN__astart                                   0x1E16001Eu  /* seed */
#define FN__cinit                                    0x1E1600E4u  /* seed */
#define FN_exit                                      0x1E1601A8u  /* seed */
#define FN__exit                                     0x1E1601BFu  /* seed */
#define FN__ctermsub                                 0x1E160206u  /* seed */
#define FN__initterm                                 0x1E160233u  /* seed */
#define FN__FF_MSGBANNER                             0x1E160246u  /* seed */
#define FN__chkstk                                   0x1E160270u  /* seed */
#define FN__nullcheck                                0x1E160294u  /* seed */
#define FN__setargv                                  0x1E1602BAu  /* seed */
#define FN__NMSG_TEXT                                0x1E1604BAu  /* seed */
#define FN__NMSG_WRITE                               0x1E1604E5u  /* seed */
#define FN__myalloc                                  0x1E160510u  /* seed */
#define FN__dosmaperr                                0x1E160578u  /* seed */
#define FN_flushall                                  0x1E1605A6u  /* seed */
#define FN_lseek                                     0x1E16136Eu  /* seed */
#define FN_write                                     0x1E1613E8u  /* seed */
#define FN_stackavail                                0x1E161512u  /* seed */
#define FN_free                                      0x1E161526u  /* seed */
#define FN_malloc                                    0x1E161538u  /* seed */
#define FN__ffree                                    0x1E16157Eu  /* platform */
#define FN__fmalloc                                  0x1E161593u  /* platform */
#define FN__brkctl                                   0x1E1617BCu  /* seed */
#define FN_strcpy                                    0x1E161880u  /* seed */
#define FN_strlen                                    0x1E1618B2u  /* seed */
#define FN_itoa                                      0x1E1619D0u  /* seed */
#define FN_isatty                                    0x1E161ADCu  /* seed */
#define FN_kbhit                                     0x1E161B6Eu  /* platform */
#define FN_getch                                     0x1E161B82u  /* platform */
#define FN_int86                                     0x1E161B9Au  /* platform */
#define FN_sprintf                                   0x1E161C8Eu  /* seed */
#define FN_int86x                                    0x1E161CE8u  /* platform */
#define FN_intdos                                    0x1E161D7Eu  /* platform */
#define FN_movedata                                  0x1E161DC8u  /* platform */
#define FN_segread                                   0x1E161DE6u  /* platform */
#define FN_time                                      0x1E161DFCu  /* platform */
#define FN_stricmp                                   0x1E162130u  /* seed */
#define FN_memset                                    0x1E162240u  /* seed */
#define FN_remove                                    0x1E1622DEu  /* platform */
#define FN__bios_equiplist                           0x1E1622ECu  /* platform */
#define FN__dos_close                                0x1E1622F0u  /* platform */
#define FN__dos_creat                                0x1E162305u  /* platform */
#define FN__dos_getvect                              0x1E16231Eu  /* platform */
#define FN__dos_open                                 0x1E162330u  /* platform */
#define FN__dos_read                                 0x1E162348u  /* platform */
#define FN__dos_write                                0x1E16234Fu  /* platform */
#define FN__dos_setvect                              0x1E16236Cu  /* platform */
#define FN__dos_getdrive                             0x1E162382u  /* seed */
#define FN__harderr                                  0x1E162396u  /* platform */
#define FN__hardresume                               0x1E1623E3u  /* platform */
#define FN__aFldiv                                   0x1E1623ECu  /* platform */
#define FN__aFlmul                                   0x1E162488u  /* seed */
#define FN__aFlshr                                   0x1E16255Eu  /* platform */
#define FN__aFaldiv                                  0x1E16256Au  /* platform */
#define FN_delay                                     0x21960002u  /* sound, void far (u16 n) */
#define FN_pulse3_play                               0x2196001Du  /* sound, void far (u16 *list) */
#define FN_ega_wait_vretrace                         0x21A00006u  /* video, far void (void) */
#define FN_ega_set_split                             0x21A00014u  /* video, far void (int line) */
#define FN_tdy_blit_masked                           0x21A00358u  /* video */
#define FN_tdy_blit                                  0x21A004ABu  /* video */
#define FN_tdy_blit_shifted                          0x21A007ACu  /* video */
#define FN_tdy_install_vectors                       0x21A00952u  /* video, far void (void) */
#define FN_tdy_draw_text                             0x21A00964u  /* video */
#define FN_tdy_recolour_rect                         0x21A00A4Fu  /* video */
#define FN_tdy_copy_page                             0x21A00C09u  /* video */
#define FN_tdy_blinds                                0x21A00C26u  /* video */
#define FN_tdy_anim_step                             0x21A00D62u  /* video */
#define FN_ega_install_vectors                       0x21A01128u  /* video, far void (void) */
#define FN_ega_draw_text                             0x21A0113Au  /* video, far void (Desc far *d; int x; int y; char *s) */
#define FN_ega_recolour_rect                         0x21A01508u  /* video, far void (Desc far *d; int from; int to; int x0; */
#define FN_ega_copy_page                             0x21A016DCu  /* video, far int (u8 far *src; u8 far *dst) */
#define FN_ega_blinds                                0x21A01722u  /* video, far int (u8 far *dst; u8 far *src) */
#define FN_ega_show_page                             0x21A0182Eu  /* video, far void (int page) */
#define FN_ega_blit                                  0x21A01862u  /* video, far u16 (Desc far *src; Desc far *dst; Rect *r;  */
#define FN_ega_sprite_over_bg                        0x21A01AE9u  /* video, far int (Desc far *spr; Desc far *dst; Desc far  */
#define FN_ega_blit_masked                           0x21A01CD5u  /* video, far int (Desc far *src; Desc far *dst; Rect *r;  */
#define FN_ega_save_rect                             0x21A01E2Du  /* video, far void (u8 far *src; int w; int h; u8 far *dst */
#define FN_shift_row                                 0x21A01EA2u  /* video, near void (u8 *row; int shift; int n) */
#define FN_ega_put_shifted_row                       0x21A01F8Du  /* video, near void (u8 far *dst; u8 *buf4; int w; int bit */
#define FN_ega_blit_shifted                          0x21A0223Bu  /* video, far void (Desc far *src; Desc far *dst; Rect *r) */
#define FN_ega_line                                  0x21A023BCu  /* video, far void (int x0; int y0; int x1; int y1; int co */
#define FN_ega_pixel_addr_21A0_252E                  0x21A0252Eu  /* video, near asm */
#define FN_ega_get_pixel                             0x21A0254Du  /* video, near asm */
#define FN_anim_restore_rect                         0x21A02568u  /* video, near void (i16 *r; Desc far *page; Desc far *bg; */
#define FN_ega_anim_step                             0x21A025D9u  /* video, far int (Anim *a) */
#define FN_ega_slide_sprite                          0x21A028ECu  /* video, far void (int top; int bottom; int x; int from;  */
#define FN_far_memmem                                0x24600002u  /* platform, far int (char *pat; void far *buf; int len) */
#define FN_ega_latch_copy                            0x24E70008u  /* video, far void (u8 far *src; u8 far *dst; int wb; int  */
#define FN_ega_latch_copy_to40                       0x24E7008Bu  /* video, far void (u8 far *src; int wb; int h; u8 far *ds */
#define FN_rows_composite                            0x24F4000Au  /* video, far void (u8 far *dst; u16 seg; u16 src; u16 mas */
#define FN_rows_mask_or                              0x25950004u  /* video, far void (u8 far *dst; u16 seg; u16 src; u16 mas */
#define FN_rows_mask_blend                           0x2634000Au  /* video, far void (u8 far *dst; u16 seg; u16 src; u16 mas */
#define FN_make_mask_plane                           0x263400C1u  /* video, far void (u8 far *planes; u8 far *mask; u16 tota */
#define FN_road_fillmode_begin                       0x26450008u  /* race, far void(void) */
#define FN_road_fillmode_end                         0x2645001Du  /* race, far void(void) */
#define FN_ega_hline                                 0x26450034u  /* race, far void(int x1,int x2,int y,int c) */
#define FN_ega_fill_rows                             0x264500E7u  /* race, far void(int y,int c) */
#define FN_ega_pixel_addr_2645_014B                  0x2645014Bu  /* race, near (AX=y,BX=x)->ES:BX,CL */
#define FN_track_rnd                                 0x2645016Au  /* race, near int(int n) */
#define FN_track_feat_curve_left                     0x2645017Au  /* race, near void(void) */
#define FN_track_feat_curve_right                    0x26450293u  /* race, near void(void) */
#define FN_track_feat_s_bend_left                    0x264503A8u  /* race, near void(void) */
#define FN_track_feat_s_bend_right                   0x26450539u  /* race, near void(void) */
#define FN_track_feat_hill                           0x264506CAu  /* race, near void(void) */
#define FN_track_feat_dip                            0x2645075Du  /* race, near void(void) */
#define FN_track_feat_hills_long                     0x264507F2u  /* race, near void(void) */
#define FN_track_feat_dips_long                      0x26450885u  /* race, near void(void) */
#define FN_track_feat_roadworks_right                0x2645091Au  /* race, near void(void) */
#define FN_track_feat_narrow_bridge                  0x264509F0u  /* race, near void(void) */
#define FN_track_feat_roadworks_left                 0x26450ABBu  /* race, near void(void) */
#define FN_track_build_course                        0x26450B91u  /* race, far void(int arg) */
#define FN_track_build_all                           0x26450D48u  /* race, far void(void) */
#define FN_road_set_seg_ptrs                         0x2645171Du  /* race, far void(int seg) */
#define FN_road_proj_x                               0x2645176Fu  /* race, far int(int z,int x,int dx) */
#define FN_road_proj_y                               0x264517B1u  /* race, far int(int z,int y,int dy) */
#define FN_road_proj_x_mirror                        0x264517EDu  /* race, far int(int z,int x,int dx) */
#define FN_road_proj_y_mirror                        0x26451828u  /* race, far int(int z,int y,int dy) */
#define FN_road_state_init                           0x2645185Du  /* race, far void(void) */
#define FN_road_project_front                        0x264518FBu  /* race, far void(void) */
#define FN_road_project_mirror                       0x26451BCCu  /* race, far void(void) */
#define FN_road_frame                                0x26451E9Eu  /* race, far void(void) */
#define FN_road_advance_segment                      0x26451EFCu  /* race, far void(void) */
#define FN_road_edge_collision                       0x2645206Bu  /* race, far int(void) */
#define FN_road_race_init                            0x26452114u  /* race, far void(void) */
#define FN_road_nudge_heading                        0x26452126u  /* race, far void(int dir) */
#define FN_road_step                                 0x2645213Du  /* race, far void(void) */
#define FN_road_pages_init                           0x2645224Eu  /* race, near void(void) */
#define FN_road_page_flip                            0x26452288u  /* race, near void(void) */
#define FN_blit_clip_y                               0x264522FCu  /* race, near void(Rect *r) */
#define FN_blit_clip_xy                              0x26452331u  /* race, near void(Rect *r) */
#define FN_road_vline                                0x26452381u  /* race, near void(int c,int x,int y1,int y2) */
#define FN_clip_set_ymin0                            0x264523F0u  /* race, far void(void) */
#define FN_clip_set_mirror                           0x264523F7u  /* race, near void(void) */
#define FN_clip_set_view                             0x26452410u  /* race, far void(void) */
#define FN_road_load_graphics                        0x26452429u  /* race, far void(void) */
#define FN_road_draw_sky                             0x26452982u  /* race, near void(void) */
#define FN_shape_draw                                0x26452C0Au  /* race, far void(int x,int y,int size,int nsizes,ShapeSi */
#define FN_slope16                                   0x26452CFCu  /* race, near int(int xa,int ya,int xb,int yb) */
#define FN_quad_fill                                 0x26452D20u  /* race, near void(int c,int x0,int x1,int y0,int y1,int  */
#define FN_sign_2645_2F2B                            0x26452F2Bu  /* race, near int(int v) */
#define FN_road_draw_band_front                      0x26452F48u  /* race, far void(int row) */
#define FN_road_draw_band_mirror                     0x2645324Du  /* race, far void(void) */
#define FN_town_walls_front                          0x264534DAu  /* race, near void(int a,int b,int c,int d,int e,int f,in */
#define FN_town_walls_mirror                         0x264537AFu  /* race, near void(int a,int b,int c,int d,int e,int f,in */
#define FN_town_walls_front_left                     0x264539DEu  /* race, near void(void) */
#define FN_town_walls_front_right                    0x26453A0Du  /* race, near void(void) */
#define FN_road_draw_row_front                       0x26453A3Bu  /* race, near void(int row) */
#define FN_town_walls_mirror_left                    0x26453A57u  /* race, near void(void) */
#define FN_town_walls_mirror_right                   0x26453A86u  /* race, near void(void) */
#define FN_road_draw_row_mirror                      0x26453AB4u  /* race, near void(void) */
#define FN_shape_draw_dot                            0x26453ABFu  /* race, far void(int x,int y) */
#define FN_scenery_draw_shape                        0x26453AEBu  /* race, near void(int x,int y,int depth,int side,int typ */
#define FN_scenery_draw_hydrant                      0x26453B3Au  /* race, near void(int x,int y,int depth,int side) */
#define FN_scenery_draw_sign_picture                 0x26453B79u  /* race, near void(int x,int y,int depth,int align,int xc */
#define FN_scenery_draw_banner                       0x26453CCCu  /* race, near void(int xl,int xr,int ytop,int ybot,int de */
#define FN_road_draw_start_light                     0x26453DC3u  /* race, near void(void) */
#define FN_road_draw_cockpit_overlay                 0x26453E3Cu  /* race, near void(void) */
#define FN_mirror_draw_background                    0x26453EDBu  /* race, near void(void) */
#define FN_opponent_draw                             0x26453F8Du  /* race, near void(void) */
#define FN_road_draw_mirror                          0x264543FDu  /* race, near void(void) */
#define FN_road_draw_frame                           0x26454B8Cu  /* race, far void(void) */
#define FN_road_first_frame                          0x2645527Au  /* race, far void(void) */
#define FN_popcount8                                 0x2645528Cu  /* race, near int(uint8 m) */
#define FN_pic_alloc_shrunk                          0x264552B7u  /* race, near Pic far *(Pic far *src,uint8 ymask,uint8 xm */
#define FN_pic_shrink_planar                         0x26455407u  /* race, far Pic far *(Pic far *src,uint8 ymask,uint8 xma */
#define FN_cga_expand_bits                           0x264555F8u  /* race, near void(uint8 m,uint8 *hi,uint8 *lo) */
#define FN_pic_shrink_cga                            0x26455670u  /* race, far Pic far *(Pic far *,uint8,uint8) */
#define FN_pic_shrink_tandy                          0x26455885u  /* race, far Pic far *(Pic far *,uint8,uint8) */
